# 設定は以下を参考
# https://www.digitalocean.com/community/tutorials/how-to-set-up-flask-with-mongodb-and-docker
version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: task_manager_db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: Bn9kRGjL
      MONGODB_HOSTNAME: db
    volumes:
      - .:/var/www
    depends_on:
      - mongodb    
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:4.4.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: b8R2azvc
      MONGO_INITDB_DATABASE: task_manager_db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodbdata:/data/db
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# volumes:
#   mongodbdata:
#     driver: local
#   appdata:
#     driver: local
#   nginxdata:
#     driver: local